apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: pgadmin
  name: pgadmin
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    service: pgadmin
status:
  loadBalancer: {}
