apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: webapi
  name: webapi
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    service: webapi
status:
  loadBalancer: {}
